### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#10]
The https://www.ibm.com/cloud/architecture/architectures/edit/architect-assistant page states to see the FAQ section for troubleshooting but there is no section in the installation guide with this name.

**Comment by carlosbittrich** [comment]
Correction, there is a header for FAQ but it is not in the introduction of the document as a section.

**Comment by glcraig** [comment]
But there is an FAQ section and that is where the troubleshooting details are found - https://github.com/IBM/itaa-docs/blob/master/docs/community-edition/Install.md#faq

**Comment by carlosbittrich** [comment]
I think the correction is just to include FAQ in the list of sections in the introduction of the document.
