### ISSUE TITLE
Use case "sort by"

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#11]
The Use case artifact should remember the last "sort by" defined. Each time I enter a use case description and go back to the list, the order of the use cases return to creation date. This is not critical but annoying.

**Comment by carlosbittrich** [comment]
No comments for this?

**Comment by glcraig** [comment]
There are a number of backlog enhancements in this space.  Among them remember filter and sort by for all artifact instance types.  In addition adding filter by - Use Case Package Name (Epic) in addition to Actor.

**Comment by glcraig** [comment]
Fixed.
