### ISSUE TITLE
How to upload IT Architect Assistant files.

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#16]
Hello, I hope you are taken care now. 
The https://www.ibm.com/cloud/architecture/architectures/edit/architect-assistant page now includes a step 4 (Download the IT Architect Assistant files). 
Please can you provide instructions for installing them. 
Thanks in advance.

**Comment by glcraig** [comment]
See details both in user guide and now linked tutorial - https://github.com/IBM/itaa-docs/blob/master/docs/community-edition/Overview-ITAA-CE.md#getting-started
