### ISSUE TITLE
“ca-offline-macos” cannot be opened

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#17]
Hello, I suggest you include some guidelines or instructions for the _“ca-offline-macos” cannot be opened because the developer cannot be verified._ message. 
I a using MACOS Catalina Version 10.15.6. 
Regards.

**Comment by glcraig** [comment]
See the install guide.   This is clearly documented in the FAQ section!

**Comment by carlosbittrich** [comment]
Ups, sorry ;-). I forgot to read further down. 
By the way, just copied the old workspace and I see my old stuff. 
Bye Gary.
