### ISSUE TITLE
Source/package not available

### ISSUE THREAD

**Issue by CHB83** [IBM/itaa-docs#2]
It's said in the Install.md for CE : 
_Currently, the community edition is provided via a zip file in Github for downloading. After downloading, unzipping and installing, you can use it on your local system._

Problem : no package on github to download.

**Comment by glcraig** [comment]
The link to IBM Cloud Architecture center and download has been added to the doc.
https://www.ibm.com/cloud/architecture/architectures/edit/architect-assistant
