### ISSUE TITLE
Unable to export images

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#20]
Hello, I haven't used Cognitive Architect for a while but now when I try to export a file I get an error message when exporting to ppt and in the case of word format I get the text but not the included images. I am including the log and har files of the run. 
[CAA.log](https://github.com/IBM/itaa-docs/files/6160332/CAA.log)
[CAA.har.zip](https://github.com/IBM/itaa-docs/files/6160337/CAA.har.zip)
Any idea what I am missing? 
I am using the latest version: Version V3.2.2
Regards.

**Comment by carlosbittrich** [comment]
By the way, i am also getting some messages about deprecated ...

_express deprecated res.send(status): Use res.sendStatus(status) instead ../../../../snapshot/CA-APP/offline_server.js:36:36
express deprecated res.send(status, body): Use res.status(status).send(body) instead ../../../../snapshot/CA-APP/offline_server.js:653:23__

**Comment by glcraig** [comment]
Make sure your local tomcat (in the CAAppOffline) is compatible with your OS.  (Big Sur for instance requires updated tomcat).   Before I upgraded (full reinstall of ITAA-CE including tomcat and jre) - I had issues with export of images.   Afterwords, everything works as expected.

**Comment by carlosbittrich** [comment]
Thanks amigo. 
You were right. I removed an reinstalled tomcat and JRE and now it is working. 
Take care. 
Carlos
