### ISSUE TITLE
How to depict cloud services in Physical Operational Model

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#24]
In the POM you can define Prescribed, Virtual and Container Nodes but there is nothing equivalent to the physical description of a cloud service. For example if I want to describe a "Cloud Object Storage", I can define a "logical node" named "Object Storage" but there should be a "physical node" corresponding to it with a name that is defined in the IBM Cloud Resource List.

**Comment by glcraig** [comment]
You might choose to name a Logical Node - Cloud Object Storage, but the deployed functionality will be represented as a Deployment Unit that is tied to a Logical Component, e.g. Cloud Storage Service, with an Implementation which is IBM Cloud Object Storage (for example).

**Comment by carlosbittrich** [comment]
Ok my friend. Yes, i forgot that I have the Deployment Units and I think I will use them to name them with the IBM Cloud resource name. Take care.
