### ISSUE TITLE
Copyright message in PPT

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#5]
The ppowerpoint templates include an IBM copyright message. The options, a) if it must be legaly included, change to a more current date. It states 2017 and ITAA was released in 2019. b) if we consdier that the architecture is owned by the user, this should be deleted.

**Comment by glcraig** [comment]
This too will be corrected!

**Comment by carlosbittrich** [comment]
Thanks Gary. I hope you are doing well.
