### ISSUE TITLE
Github and co-relationshop not available in community edition

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#8]
From https://github.com/IBM/itaa-docs/blob/master/docs/community-edition/Overview-ITAA-CE.md  the community edition should shpport this features. It seems to me that the documentation is confusing between offline (enterprise) and community edition as many features are not available. Please can you synchronize the text with the features available.

**Comment by glcraig** [comment]
Sorry for the confusion.  The docs have been updated to reflect current supported features in Community Edition.
